### ISSUE TITLE
#Missing texture reference

### ISSUE THREAD

**Issue by Prospector** [CoolMineman/crusade#2]
I believe BlockBench includes these `#missing` texture things in models, but Minecraft expects every texture referred to to exist and spits a warning. I believe you just have to remove the face if it's not meant to have a texture.

`[18:03:31] [Worker-Main-6/WARN]: Unable to resolve texture reference: #missing in crusade:item/great_helm`

**Comment by CoolMineman** [comment]
Fixed in 1.1.0
